public class Test01 {
    public static void main(String[] args) throws Exception {

        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");
        System.out.println("");

        System.out.println("Test 01");

        int[] array = { 1, 2, 3 };

        Test01 app = new Test01();
        int result = app.solution(array);
        System.out.println("result :");
        System.out.println(result);
    }

    //
    public int solution(int[] A) {

        // 결과 반환값
        int result = 0;

        return result;
    }

}
